version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Node.js dependencies...
      - cd projects-web
      - npm ci
  build:
    commands:
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://$S3_BUCKET --delete --cache-control "public, max-age=31536000, immutable"
      - echo Frontend deployed successfully
artifacts:
  files:
    - '**/*'
  base-directory: projects-web/dist





