/**
 * Page definitions per app — aligned with ALLPAGES.md
 * Static routes only; dynamic :id routes use placeholder or are skipped for smoke.
 */
export const APP_PAGES: Record<string, { path: string; auth?: boolean }[]> = {
  'taskjuggler-web': [
    { path: '/', auth: false },
    { path: '/login', auth: false },
    { path: '/register', auth: false },
    { path: '/forgot-password', auth: false },
    { path: '/reset-password', auth: false },
    { path: '/profile', auth: true },
    { path: '/subscribe', auth: true },
    { path: '/dashboard', auth: true },
    { path: '/tasks', auth: true },
    { path: '/tasks/new', auth: true },
    { path: '/inbox', auth: true },
    { path: '/routing', auth: true },
    { path: '/teams', auth: true },
    { path: '/messages', auth: true },
    { path: '/channels', auth: true },
    { path: '/marketplace', auth: true },
    { path: '/contacts', auth: true },
    { path: '/team', auth: true },
    { path: '/test-results', auth: true },
  ],
  'coordinator-web': [
    { path: '/', auth: false },
    { path: '/login', auth: false },
    { path: '/register', auth: false },
    { path: '/forgot-password', auth: false },
    { path: '/reset-password', auth: false },
    { path: '/profile', auth: true },
    { path: '/subscribe', auth: true },
    { path: '/onboarding', auth: true },
    { path: '/dashboard', auth: true },
    { path: '/coordinators', auth: true },
    { path: '/contacts', auth: true },
    { path: '/appointments', auth: true },
    { path: '/calls', auth: true },
    { path: '/calendar', auth: true },
    { path: '/analytics', auth: true },
    { path: '/billing', auth: true },
    { path: '/campaigns', auth: true },
    { path: '/settings', auth: true },
    { path: '/learning', auth: true },
  ],
  'ideacircuit-web': [
    { path: '/', auth: false },
    { path: '/login', auth: false },
    { path: '/signup', auth: false },
    { path: '/forgot-password', auth: false },
    { path: '/reset-password', auth: false },
    { path: '/subscribe', auth: true },
    { path: '/presentation', auth: true },
    { path: '/report', auth: true },
    { path: '/marketing-report', auth: true },
    { path: '/business-profile', auth: true },
    { path: '/data-analytics', auth: true },
    { path: '/client-proposal', auth: true },
    { path: '/ai-workflow', auth: true },
    { path: '/files', auth: true },
    { path: '/profile', auth: true },
    { path: '/schedule', auth: true },
  ],
  'official-notice-web': [
    { path: '/', auth: false },
    { path: '/dashboard', auth: true },
    { path: '/milestones', auth: true },
    { path: '/settings/team', auth: true },
    { path: '/settings/billing', auth: true },
    { path: '/login', auth: false },
    { path: '/register', auth: false },
  ],
  'process-web': [
    { path: '/', auth: false },
    { path: '/login', auth: false },
    { path: '/register', auth: false },
    { path: '/forgot-password', auth: false },
    { path: '/reset-password', auth: false },
    { path: '/profile', auth: true },
    { path: '/subscribe', auth: true },
    { path: '/processes', auth: true },
    { path: '/processes/new', auth: true },
    { path: '/executions', auth: true },
  ],
  'projects-web': [
    { path: '/', auth: false },
    { path: '/login', auth: false },
    { path: '/register', auth: false },
    { path: '/forgot-password', auth: false },
    { path: '/reset-password', auth: false },
    { path: '/app/profile', auth: true },
    { path: '/app/subscribe', auth: true },
    { path: '/app/projects', auth: true },
    { path: '/app/projects/new', auth: true },
  ],
  'scanner-web': [
    { path: '/', auth: false },
    { path: '/dashboard', auth: true },
    { path: '/login', auth: false },
    { path: '/register', auth: false },
    { path: '/forgot-password', auth: false },
    { path: '/reset-password', auth: false },
    { path: '/profile', auth: true },
    { path: '/subscribe', auth: true },
    { path: '/sites', auth: true },
    { path: '/settings', auth: true },
    { path: '/upgrade', auth: true },
  ],
  'urpa-web': [
    { path: '/', auth: false },
    { path: '/dashboard', auth: true },
    { path: '/login', auth: false },
    { path: '/signup', auth: false },
    { path: '/forgot-password', auth: false },
    { path: '/reset-password', auth: false },
    { path: '/profile', auth: true },
    { path: '/setup', auth: true },
    { path: '/subscribe', auth: true },
    { path: '/settings', auth: true },
    { path: '/calls', auth: true },
    { path: '/inbox', auth: true },
    { path: '/calendar', auth: true },
    { path: '/webhooks', auth: true },
  ],
};
